// ADAMING_SUIVI_APP-REST/src/ADAMING_SUIVI_ANGULAR/src/app/views/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { getStyle, hexToRgba } from '@coreui/coreui/dist/js/coreui-utilities';
import { CustomTooltips } from '@coreui/coreui-plugin-chartjs-custom-tooltips';
import { ChargeRelance } from '../../models/ChargeRelance';
import { SessionReporting } from '../../models/SessionReporting';
import { SourceurTechnologies } from '../../models/SourceurTechnologies';
import { AccueilService } from '../../services/accueilService/accueil.service';
import { TechnologieService } from '../../services/administrationService/TechnologieService';
import { first } from 'rxjs/operators';
import { NAVIGATION_RULES,ChartColors } from '../../helper/application.constant';
import { NotifierService } from 'angular-notifier';
import { HelperService } from '../../helper/helper.service';
import 'chart.piecelabel.js';

@Component({
  templateUrl: 'dashboard.component.html'
})
export class DashboardComponent implements OnInit {
  ReportingChargeRelance= [];
  Sessionreporting= [];
  Sourceurtechnologies= [];
  pieChartLabels: string[]=[];
  pieChartData: number[] = [];
  pieChartType = 'pie';
  ChartColors : any[]=ChartColors
  chartOptionss = {}
   nbreTotal= 0;
  constructor(
    private accueilService: AccueilService,
    private router:Router, private notifierService: NotifierService,
    private helperService: HelperService) {

     }

  ngOnInit() {
    this.loadReportingChargeRelance();
    this.loadSessionReporting();
    this.loadSourceurtechnologies();
    this.getChart();
  }

  private loadReportingChargeRelance() {
    this.accueilService.getNombreCVRrelancer().subscribe(result => { this.ReportingChargeRelance = result });
  }
   private loadSessionReporting() {
    this.accueilService.getSessionreporting().subscribe(result => {  this.Sessionreporting = result});
  }
  
  private loadSourceurtechnologies() {
    this.accueilService.getSourceurTechnologies().subscribe(result => { this.Sourceurtechnologies = result });
  }

  private getChart(){
    this.accueilService.getNombreTechnologieParCandidat().subscribe(result => { 
      this.chartOptionss = {
        pieceLabel: {
          render: function (args) {
            const value = args.value;
            var tooltipPercentage = Math.round((value / result) * 100)
            if(tooltipPercentage > 10)
            return tooltipPercentage + '%';
            else
            return null;
          }
        }
      }
    });
    this.accueilService.getChart().subscribe(result => { 
      this.pieChartData = Object.values(result);
      for(var i=0;i<Object.keys(result).length;i++){
        this.pieChartLabels[i]=Object.keys(result)[i];
      }
    });
  }

  openDetailsSession(session){
    this.router.navigate(["/"+NAVIGATION_RULES.dashboard.url+"/"+NAVIGATION_RULES.dashboard.ficheCandidatSession.replace(":id",session.idSession)])
  }

  openDetailsCVRelance(charge){
    this.router.navigate(["/"+NAVIGATION_RULES.dashboard.url+"/"+NAVIGATION_RULES.dashboard.ficheCvRelance.replace(":id",charge.idUser)])
  }
}

<div class="animated fadeIn">
    <div class="row">
      <div class="col-sm-6">
        <div class="card" style="height: 95% !important;">
          <div class="card-header">
            <label style="font-weight:bold;color:#546E7A;">CV en attente de traitement</label>
          </div>
          <div class="card-body" >
              <canvas baseChart class="chart"
              [data]="pieChartData"
              [labels]="pieChartLabels"
              [colors]="ChartColors"
              [chartType]="pieChartType"></canvas>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-header">
            <label style="font-weight:bold;color:#546E7A;">Nombre de CV à relancer par chargé de recrutement</label>
            </div>
          <div class="card-body">
            <table class="table table-bordered table-striped" >
              <thead>
                <tr>
                  <th>Chargé recrutement</th>
                  <th>Nombre CV à relancer</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let charge of ReportingChargeRelance| paginate: { itemsPerPage:5, currentPage: p }">
                  <td>{{charge.nomCharge}}</td>
                  <td>{{charge.nombreCvRelance}}</td>
                  <td style="width: 10%">     
                    <a class="btn btn-default" (click)="openDetailsCVRelance(charge)" >
                          <i class="cui-magnifying-glass icons font-xl d-block mt-2"></i>
                        </a>         
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="panel-footer panel-default pager">
              <ul class="pagination justify-content-center">
                  <li [class.disabled]="1==currentPage" class="page-item">
                      <a (click)="setPage(1)" class="page-link">«</a>
                  </li>
                  <li [class.disabled]="1==currentPage" class="page-item">
                      <a (click)="setPage(currentPage-1)" class="page-link">‹</a>
                  </li>
                  <li [class.active]="p==currentPage" class="page-item" *ngFor=" let p of pages">
                      <a class="page-link" (click)="setPage(p)">{{p}}</a>
                  </li>
                  <li [class.disabled]="currentPage==lastPage" class="page-item">
                      <a (click)="setPage(currentPage+1)" class="page-link">›</a>
                  </li>
                  <li [class.disabled]="currentPage==lastPage" class="page-item">
                      <a (click)="setPage(lastPage)" class="page-link">»</a>
                  </li>
              </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-header">
            <label style="font-weight:bold;color:#546E7A;">Sessions de formation</label>
          </div>
          <div class="card-body" >
            <table class="table table-bordered table-striped table-sm " style="font-size: 0.6rem !important;">
              <thead>
                <tr>
                  <th>Nom de la formation</th>
                  <th>Lieu de la formation</th>
                  <th>Type de formation</th>
                  <th>Date Démarrage</th>
                  <th>Candidat validé par C.R.</th>
                  <th>Candidat ayant accepté la formation</th>
                  <th>Nombre de place</th>
                  <th>Taux d'acceptation</th>
                  <th>Taux de remplissage</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody >
                <tr *ngFor="let session of Sessionreporting| paginate: { itemsPerPage:5, currentPage: p }">
                  <td >{{session.nom_Formation}}</td>
                  <td>{{session.lieu_Formation}}</td>
                  <td>{{session.type_Formation}}</td>
                  <td>{{session.date_demarrage}}</td>
                  <td>{{session.candidat_affectation}}</td>
                  <td>{{session.candidat_acceptation}}</td>
                  <td>{{session.nombre_place}}</td>
                  <td>{{session.taux_acceptation}}</td>
                  <td>{{session.taux_remplissage}}%</td>
                  <td style="width: 10%">     
                    <a class="btn btn-default" (click)="openDetailsSession(session)">
                          <i class="cui-magnifying-glass icons font-xl d-block mt-2"></i>
                        </a>         
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="panel-footer panel-default pager">
              <ul class="pagination justify-content-center">
                  <li [class.disabled]="1==currentPage" class="page-item">
                      <a (click)="setPage(1)" class="page-link">«</a>
                  </li>
                  <li [class.disabled]="1==currentPage" class="page-item">
                      <a (click)="setPage(currentPage-1)" class="page-link">‹</a>
                  </li>
                  <li [class.active]="p==currentPage" class="page-item" *ngFor=" let p of pages">
                      <a class="page-link" (click)="setPage(p)">{{p}}</a>
                  </li>
                  <li [class.disabled]="currentPage==lastPage" class="page-item">
                      <a (click)="setPage(currentPage+1)" class="page-link">›</a>
                  </li>
                  <li [class.disabled]="currentPage==lastPage" class="page-item">
                      <a (click)="setPage(lastPage)" class="page-link">»</a>
                  </li>
              </ul>
          </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-header">
              <label style="font-weight:bold;color:#546E7A;">Nombre de CV intégrés au niveau de l'application
                </label>
          </div>
          <div class="card-body">
              <table class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Sourceur</th>
                      <th>Mainframe</th>
                      <th>Mainframe++</th>
                      <th>NTIC</th>
                      <th>Autres technologies</th>
                      <th>TOTAL</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr *ngFor="let technologie of Sourceurtechnologies| paginate: { itemsPerPage:3, currentPage: p }">
                      <td>{{technologie.nom}}</td>
                      <td>{{technologie.nbrCvMainframe}}</td>
                      <td>{{technologie.nbrCvMainframePlus}}</td>
                      <td>{{technologie.nbrCvNtic}}</td>
                      <td>{{technologie.autreTechnologie}}</td>
                      <td>{{technologie.total}}</td>
                    </tr>
                  </tbody>
                </table>
               <!-- <div class="panel-footer panel-default pager">
                    <pagination-controls (pageChange)="p =$event"></pagination-controls>
                  </div>-->
                  <div class="panel-footer panel-default pager">
                    <ul class="pagination justify-content-center">
                        <li [class.disabled]="1==currentPage" class="page-item">
                            <a (click)="setPage(1)" class="page-link">«</a>
                        </li>
                        <li [class.disabled]="1==currentPage" class="page-item">
                            <a (click)="setPage(currentPage-1)" class="page-link">‹</a>
                        </li>
                        <li [class.active]="p==currentPage" class="page-item" *ngFor=" let p of pages">
                            <a class="page-link" (click)="setPage(p)">{{p}}</a>
                        </li>
                        <li [class.disabled]="currentPage==lastPage" class="page-item">
                            <a (click)="setPage(currentPage+1)" class="page-link">›</a>
                        </li>
                        <li [class.disabled]="currentPage==lastPage" class="page-item">
                            <a (click)="setPage(lastPage)" class="page-link">»</a>
                        </li>
                    </ul>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>

// ADAMING_SUIVI_APP-REST/src/adaming-suivi-vue/src/views/Dashboard.vue
<template>
<b-card bg-variant="#FFFFFF">
<div class="panel-body">
<div class="container-fluid">
  <div class="card">
<div class="row">
<div class="col-sm-6 col-md-6">
  <div class="card">
    <b-row class="justify-content-md-center">
    <label style="font-weight:bold;color:#546E7A;ce">CV en attente de traitement</label>
    </b-row>
<canvas id="line-chart-agency" width="200" height="130"></canvas>
  </div>
</div> 
<div class="col-sm-6 col-md-6">
  <div class="card">
    <b-row class="justify-content-md-center">
    <label style="font-weight:bold;color:#546E7A;ce">Nombre de CV à relancer par chargé de recrutement
    </label>
    </b-row>
  <vue-good-table
          :columns= "
          [
        {
          label: 'Chargé recrutement',
          field: 'nomCharge',
          tdClass: 'text-center',
        },
        {
          label: 'Nombre CV à relancer',
          field: 'nombreCvRelance',
          tdClass: 'text-center',
        },
         {
          label: 'Action',
          field: 'idUser',
          tdClass: 'text-center',
          type: 'number',
       
        }
        ]"

          :rows="ReportingChargeRelance"
          :sort-options="{
            enabled: true,
            initialSortBy: {field: 'dateTache', type: 'desc'}
          }"
          :pagination-options="{
            enabled: true,
            perPage: 5,
            perPageDropdown: [5],
            nextLabel: 'Suiv',
            prevLabel: 'Préc',
            ofLabel: '/',
            allLabel: 'Tout',
            rowsPerPageLabel: 'Lignes par page',
          }"
          styleClass="vgt-table  bordered vgt-center-align">

            <template slot="table-row" slot-scope="props" >
              <span v-if="props.column.field  == 'nomCharge'">
               {{props.row.nomCharge}}
              </span>
              <span v-if="props.column.field  == 'nombreCvRelance'">
               {{props.row.nombreCvRelance}}
              </span>
               <span v-if="props.column.field  == 'idUser'">
                <router-link :to="'/ficheCVRelance/'+props.row.idUser">
                    <i  class="material-icons text-primary cursor" title="Voir fiche">visibility</i>
                </router-link>
              </span>
            </template>
             <div slot="emptystate">
                Pas des données pour la table
            </div>
        
       </vue-good-table>
  </div>
</div>
</div>
<div class="row">
  
<div class="col-sm-6 col-md-6">
  <div class="card">
    <b-row class="justify-content-md-center">
    <label style="font-weight:bold;color:#546E7A;ce">Sessions de formation</label>
    </b-row>
  <vue-good-table
          :columns= "
          [
        {
          label: 'Nom de la formation	',
          field: 'nom_Formation',
          tdClass: 'text-center',
        },
        {
          label: 'Lieu de la formation	',
          field: 'lieu_Formation',
          tdClass: 'text-center',
        },
        {
          label: 'Type de formation	',
          field: 'type_Formation',
          tdClass: 'text-center',
        },
        {
          label: 'Date Démarrage	',
          field: 'date_demarrage',
          tdClass: 'text-center',
        },
        {
          label: 'Candidat validé par C.R.',
          field: 'candidat_affectation',
          tdClass: 'text-center',
        },
        {
          label: 'Candidat ayant accepté la formation',
          field: 'candidat_acceptation',
          tdClass: 'text-center',
        },
        {
          label: 'Nombre de place',
          field: 'nombre_place',
          tdClass: 'text-center',
        },
        {
          label: 'Taux acceptation',
          field: 'taux_acceptation',
          tdClass: 'text-center',
        },
          {
          label: 'Taux de remplissage',
          field: 'taux_remplissage',
          tdClass: 'text-center',
        },
         {
          label: 'Action',
          field: 'idSession',
          tdClass: 'text-center',
          type: 'number',
       
        }
        ]"

          :rows="Sessionreporting"
          :sort-options="{
            enabled: true,
            initialSortBy: {field: 'dateTache', type: 'desc'}
          }"
          :pagination-options="{
            enabled: true,
            perPage: 5,
            perPageDropdown: [5],
            nextLabel: 'Suiv',
            prevLabel: 'Préc',
            ofLabel: '/',
            allLabel: 'Tout',
            rowsPerPageLabel: 'Lignes par page',
          }"
          styleClass="vgt-table  bordered vgt-center-align">

            <template slot="table-row" slot-scope="props" >
              <span v-if="props.column.field  == 'nom_Formation'">
               {{props.row.nom_Formation}}
              </span>
              <span v-if="props.column.field  == 'lieu_Formation'">
               {{props.row.lieu_Formation}}
              </span>
               <span v-if="props.column.field  == 'type_Formation'">
               {{props.row.type_Formation}}
              </span>
               <span v-if="props.column.field  == 'date_demarrage'">
               {{props.row.date_demarrage}}
              </span>
               <span v-if="props.column.field  == 'candidat_affectation'">
               {{props.row.candidat_affectation}}
              </span>
               <span v-if="props.column.field  == 'candidat_acceptation'">
               {{props.row.candidat_acceptation}}
              </span>
               <span v-if="props.column.field  == 'nombre_place'">
               {{props.row.nombre_place}}
              </span>
               <span v-if="props.column.field  == 'taux_acceptation'">
               {{props.row.taux_acceptation}}
              </span>
               <span v-if="props.column.field  == 'taux_remplissage'">
               {{props.row.taux_remplissage}}
              </span>
               <span v-if="props.column.field  == 'idSession'">
                <router-link :to="'/ficheCandidatSession/'+props.row.idSession">
                    <i  class="material-icons text-primary cursor" title="Voir fiche">visibility</i>
                </router-link>
              </span>
            </template>
             <div slot="emptystate">
                Pas des données pour la table
            </div>
        
       </vue-good-table>
  </div>
</div>
<div class="col-sm-6 col-md-6">
  <div class="card">
     <b-row class="justify-content-md-center">
    <label style="font-weight:bold;color:#546E7A;ce">Nombre de CV intégrés au niveau de l'application</label>
    </b-row>
  <vue-good-table
          :columns= "
          [
        {
          label: 'Sourceur',
          field: 'nom',
          tdClass: 'text-center',
        },
        {
          label: 'Mainframe',
          field: 'nbrCvMainframe',
          tdClass: 'text-center',
        },
        {
          label: 'Mainframe++',
          field: 'nbrCvMainframePlus',
          tdClass: 'text-center',
        },
        {
          label: 'NTIC',
          field: 'nbrCvNtic',
          tdClass: 'text-center',
        },
        {
          label: 'Autres technologies',
          field: 'autreTechnologie',
          tdClass: 'text-center',
        },
        {
          label: 'TOTAL',
          field: 'total',
          tdClass: 'text-center',
        }
        ]"

          :rows="SourceurTechnologies"
          :sort-options="{
            enabled: true,
            initialSortBy: {field: 'dateTache', type: 'desc'}
          }"
          :pagination-options="{
            enabled: true,
            perPage: 5,
            perPageDropdown: [5],
            nextLabel: 'Suiv',
            prevLabel: 'Préc',
            ofLabel: '/',
            allLabel: 'Tout',
            rowsPerPageLabel: 'Lignes par page',
          }"
          styleClass="vgt-table  bordered vgt-center-align">

            <template slot="table-row" slot-scope="props" >
              <span v-if="props.column.field  == 'nom'">
               {{props.row.nom}}
              </span>
              <span v-if="props.column.field  == 'nbrCvMainframe'">
               {{props.row.nbrCvMainframe}}
              </span>
              <span v-if="props.column.field  == 'nbrCvMainframePlus'">
               {{props.row.nbrCvMainframePlus}}
              </span>
              <span v-if="props.column.field  == 'nbrCvNtic'">
               {{props.row.nbrCvNtic}}
              </span>
              <span v-if="props.column.field  == 'autreTechnologie'">
               {{props.row.autreTechnologie}}
              </span>
              <span v-if="props.column.field  == 'total'">
               {{props.row.total}}
              </span>
            </template>
             <div slot="emptystate">
                Pas des données pour la table
            </div>
        
       </vue-good-table>
  </div>
</div>
  </div>
</div>
</div>
</div>
</b-card>
</template>
<script>
 import cSwitch from '@/components/Switch'
import accueilService from '@/services/AccueilService/accueilService'
import TechnologieService from '@/services/administrationService/TechnologieService'
import Chart from 'chart.js';
export default {
  components :{
    cSwitch,
    Chart
  },
  data () {
    return {
    dataPieChart : [],
    test: [],
    lib: [],
    ReportingChargeRelance : [],
    Sessionreporting : [],
    SourceurTechnologies : []
    }
  },
  computed: {
    RDVLangue() {
        return this.translate('RDVLangue')
      }
    },
   
  created(){
    var vm = this;
     accueilService.getNombreCVRrelancer().then(function(response) {
            vm.ReportingChargeRelance = response.data;
          }),
      accueilService.getSessionreporting().then(function(response) {
            vm.Sessionreporting = response.data;
          }),
      accueilService.getSourceurTechnologies().then(function(response) {
            vm.SourceurTechnologies = response.data;
          }),
    
    vm.getChart();
  },

  methods: {
    getChart() {
     var vm = this;
     TechnologieService.getTechnologiesByLibelle().then(function(response) {
            vm.test = response.data
           for (var i=0 ; i<vm.test.length ; i++) {
             vm.lib.push(vm.test[i].libelle)

           }
          }),
          
    accueilService.getChart().then(function(result) {
    if (result.status == 200) {
    if(result.data){
    vm.dataPieChart = Object.values(result.data)
                new Chart(document.getElementById("line-chart-agency"), {
    type: 'pie',
    data: {
      labels: vm.lib,
      datasets: [
        {
          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","#e67e22","#d35400"],
          data: vm.dataPieChart
        }
      ]
       }
      });
         }
            }
              })
    }
  }
}
</script>
<style scoped>

.has-error{
  color : red;
  border-color : red;
  border-block-start-color: red;
  background-color: #fff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(240, 8, 8, 0.25);
}
.danger{
  color: red
}
.star{
  color: red;
  font-weight: bold;
}
</style>
