// ADAMING_SUIVI_APP-REST/src/adaming-suivi-vue/src/views/Candidats/ListeNouveauxCandidats.vue
<template>
<div class="row">
  <!--Liste des Rendez-vous-->

<div class="col-sm-12 col-md-12">


<div>
  <div class="card-header">
  <div>
    Recherche
 </div>
  </div>
       <b-card-body class="card"  :style="{'direction' : rtl}">
           <b-row>
            <b-col sm="2">
              <b-form-group>
                <label>Nom</label>
                 <b-form-input  type="text"  placeholder="Nom" v-model="candidat.nom"></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="2">
              <b-form-group>
                <label>Prénom </label>
                <b-form-input  type="text"  placeholder="Prénom"  v-model="candidat.prenom"></b-form-input>
              </b-form-group>
            </b-col>
             <b-col sm="2">
              <b-form-group>
                <label>N° téléphone</label>
                <b-form-input  type="text"  placeholder="N° téléphone" v-model="candidat.numeroTel"></b-form-input>
                <!--<input v-mask="/\d{2}\/\d{2}\/\d{2}/" placeholder="N° téléphone" v-model="candidat.numeroTel">-->
              </b-form-group>
            </b-col>
            <b-col sm="2">
              <b-form-group>
                <label>Email</label>
                <b-form-input  type="text"  placeholder="Email" v-model="candidat.email" ></b-form-input>
              </b-form-group>
            </b-col>
             <b-col sm="2">
              <b-form-group>
                <label>Date Inscription</label>
                <date-picker Style="width:100%"
                            v-model="candidat.dateInscription" 
                            type="date"
                            lang="fr"
                            format="dd/MM/yyyy"
                            :not-after= endDate
                            not-before='01/01/1900'>
                        </date-picker>
              </b-form-group>
            </b-col>

          </b-row>
                 <b-row>
            <b-col sm="2">
              <b-form-group>
                <label>Type de profil</label>
                 
                   <b-form-select v-model="candidat.technologie" >
                   <option :value="null">-- Sélectionner --</option>
                     <option v-for="technologie in technologies">{{technologie.libelle}}</option>
              </b-form-select> 
              </b-form-group>
            </b-col>
            <b-col sm="2">
              <b-form-group>
                <label>Nom Sourceur </label>
                <b-form-input  type="text"  placeholder="Nom Sourceur" v-model="candidat.nomSourceur"></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="2">
              <b-form-group>
                <label>Prenom Sourceur</label>
                <b-form-input  type="text"  placeholder="Prenom Sourceur" v-model="candidat.prenomSourceur"></b-form-input>
              </b-form-group>
            </b-col>
             <b-col sm="2">
              <b-form-group>
                <label>Region</label>
                <b-form-input  type="text"  placeholder="Region" v-model="candidat.region" ></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="2">
              <b-form-group>
                <label>Fraicheur CV</label>
                <b-form-select v-model="candidat.critereRecheche" :options="CritereRecheche" class="mb-3" size="sm">
                <option :value="null">-- Sélectionner --</option>
                </b-form-select> 
              </b-form-group>
            </b-col>
          </b-row>
       <div>
    <b-button  @click="rechercherNouveauxCandidats()"  variant="success">Rechercher</b-button> 
    <b-button  @click="getCandidats()"  variant="danger">Annuler</b-button> 
    <b-button class="btn btn-sm" @click="ExportExcel()">
      <img src="../../assets/excel-icon.png" width="60%">
    </b-button>
  </div>
      </b-card-body>
</div>
<div class="card"  :style="{'direction' : rtl}" >
  <div class="card-header">
  <div>
  <i class="fa fa-align-justify"></i> 
  Liste nouveaux candidats  
 </div>
     <div class="btn-group pull-right" style="margin-top : -7px;">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Colonnes
        <span class="caret"></span>
      </button>


      <ul id="my-checklist" class="dropdown-menu checklist ">

        <li>
          <label>
            <input type="checkbox"> Nom
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> Prenom
         
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> N° Tel</label>
        </li>
        <li>
          <label>
            <input type="checkbox"> email
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> mobiliteLille
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> dateinscription
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> statut
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> technologie
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> region
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> nomSourceur
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> prenomSourceur
          </label>
        </li>
      </ul>
    </div>
  </div>

   <vue-good-table
          :columns= "
          [
        {
          label: 'Nom',
          field: 'nom',
          tdClass: 'text-center',
         
        },
         {
          label: 'Prénom',
          field: 'prenom',
          tdClass: 'text-center',
        
        },
        {
          label: 'N° Téléphone',
          field: 'numeroTel',
          tdClass: 'text-center',
         
        },
        {
          label: 'Email',
          field: 'email',
          tdClass: 'text-center',
         
        },
        {
          label: 'Date inscription',
          field: 'dateInscription',
          type: 'date',
          dateInputFormat: 'YYYY-MM-DD HH:mm:ss',
          dateOutputFormat: 'DD/MM/YYYY',
          tdClass: 'text-center',
         
        },
        {
          label: 'Type de profil',
          field: 'technologie',
          tdClass: 'text-center',
         
        },
        {
          label: 'Région',
          field: 'region',
          tdClass: 'text-center',
         
        },
        {
          label: 'Nom sourceur',
          field: 'nomSourceur',
          tdClass: 'text-center',
         
        },
        {
          label: 'Prénom sourceur',
          field: 'prenomSourceur',
          tdClass: 'text-center',
        
        },
         {
          label: 'Action',
          field: 'id',
          tdClass: 'text-center',
          type: 'number',
       
        }]"

          :rows="NouveauxCandidats"
          :sort-options="{
            enabled: true,
            initialSortBy: {field: 'dateTache', type: 'desc'}
          }"
  
          styleClass="vgt-table  bordered vgt-center-align">

            <template slot="table-row" slot-scope="props" >
              <span v-if="props.column.field  == 'nom'">
               {{props.row.nom}}
              </span>
               <span v-if="props.column.field  == 'prenom'">
               {{props.row.prenom}}
              </span>
               <span v-if="props.column.field  == 'numeroTel'">
               {{props.row.numeroTel}}
              </span>
               <span v-if="props.column.field  == 'email'">
               {{props.row.email}}
              </span>
               <span v-if="props.column.field  == 'dateInscription'">
               {{timeStampToDate(props.row.dateInscription).ddmmyyyy}}
              </span>
               <span v-if="props.column.field  == 'technologie'">
               {{props.row.technologie}}
              </span>
                <span v-if="props.column.field  == 'region'">
               {{props.row.region}}
              </span>
                <span v-if="props.column.field  == 'nomSourceur'">
               {{props.row.nomSourceur}}
              </span>
                <span v-if="props.column.field  == 'prenomSourceur'">
               {{props.row.prenomSourceur}}
              </span>
              <span v-if="props.column.field  == 'id'">
                <router-link :to="/fiche-entretien/+ props.row.id">
                    <i  class="material-icons text-primary cursor" title="Voir fiche">visibility</i>
                </router-link>
              </span>
            </template>
             <div slot="emptystate">
                Pas des données pour la table
            </div>
       </vue-good-table>
      
  <!--<ul class="pagination justify-content-center">
      <li>
        <a @click="previous()" class="btn" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
     <li v-for="p in pages"
     v-if="Math.abs(p - currentPage) < 5 || p == 0">
        
          <a @click="setPage(p)"
          :class="{
          last: (p == pages - 1 && Math.abs(p - currentPage) > 10), 
          first:(p == 0 && Math.abs(p - currentPage) > 10)}">{{p}}</a>
        
    </li>
      <li>
        <a @click="next()" class="btn" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>-->
    
      
</div>
</div>
</div>
</template>
<script>
 import NouveauxcandidatService from '@/services/candidatsService/NouveauxcandidatService'
 import TechnologieService from '@/services/administrationService/TechnologieService'
 import cSwitch from '@/components/Switch'
 import moment from 'moment';
export default {
  components :{
    cSwitch
  },
  data () {
    return {
        currentPage: 0,
        warningModal: false,
        deleteVaraibale : null,
        warningModalShow: false,
        variableModalAjout : false,
        variableModalUpdate : false,
        showVaraibale : null,
      
        NouveauxCandidats : [],
        technologies : [],
         competence: {
           idCompetence : null,
           libelle : null
         },
          competenceform: {
            libelle: null
         },
           candidat: {
           idCandidat : null,
           nom : null,
           prenom : null,
           numeroTel : null,
           email : null,
           dateInscription : null,
           technologie : null,
           nomSourceur : null,
           prenomSourceur : null,
           region : null,
           mobilite : null,
           critereRecheche : null
         },
         page: 0,
         pages: [],
        size: 10,
        maxlenght: 1,
          CritereRecheche : [
        { value: '1', text: 'Moins 1 mois' },
        { value: '2', text: 'Entre 1 et 6 mois' },
        { value: '3', text: 'Plus de 6 mois' },
        
      ]
    }
  },
  computed: {
    RDVLangue() {
        return this.translate('RDVLangue')
      }
    },
  created(){
    var vm = this;
  vm.getCandidats();
  },

  methods: {
    getCandidats(){
    var vm = this;
    vm.vider();
    NouveauxcandidatService.getNouveauxCandidats(vm.page, vm.size).then(function(response) {
            vm.NouveauxCandidats = response.data;
          })
    /*NouveauxcandidatService.MaxLength().then(function(response) {
             vm.maxlenght = response.data;
      for (vm.i = 0; vm.i < (vm.maxlenght/vm.size); vm.i++) {
        vm.pages[vm.i] = (vm.i + 1);
      }
      vm.setPage(vm.i);
          }),*/
    TechnologieService.getAllTechnologies().then(function(response) {
            vm.technologies = response.data;
          });
    },       
      setPage(e) {
        var vm = this;
        vm.currentPage =e;
      vm.page = (e - 1) * 10;
      NouveauxcandidatService.getNouveauxCandidats(vm.page, vm.size).then(function(response) {
            vm.NouveauxCandidats = response.data;
          })
          
      },
      /* next(){
         var vm = this;
      vm.page = vm.page++;
      console.log("page "+vm.page+"size "+vm.size);
      NouveauxcandidatService.getNouveauxCandidats(vm.page, vm.size).then(function(response) {
            vm.NouveauxCandidats = response.data;
        })
    },  
    previous(){
         var vm = this;
      vm.page = vm.page--;
      console.log("page "+vm.page+"size "+vm.size);
      NouveauxcandidatService.getNouveauxCandidats(vm.page, vm.size).then(function(response) {
            vm.NouveauxCandidats = response.data;
        })
    },*/
      rechercherNouveauxCandidats(){
     var vm = this;
    NouveauxcandidatService.rechercheNouveauxCandidats(vm.candidat).then(function(response) {
            vm.NouveauxCandidats = response.data;
            /*console.log("size candiats "+vm.NouveauxCandidats.length)
      for (vm.i = 0; vm.i < vm.NouveauxCandidats.length; vm.i++) {
        vm.pages[vm.i] = (vm.i + 1);
      }
      vm.setPage(vm.i);*/
             })
      },
      ExportExcel() {
    var vm = this;
    NouveauxcandidatService.getNouveauxCandidatsExcel(vm.candidat).then(function(response) {
  if (response.status == 200) {
              console.log(response.data)
              /* generate a worksheet */
              var XLSX = require('xlsx')
              var ws = XLSX.utils.json_to_sheet(response.data);
              /* add to workbook */
              var wb = XLSX.utils.book_new();
              XLSX.utils.book_append_sheet(wb, ws, 'nom');
              var wbout = XLSX.write(wb, {bookType:'xlsx', type:'binary'});
              /* generate a download */
              function s2ab(s) {
                var buf = new ArrayBuffer(s.length);
                var view = new Uint8Array(buf);
                for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
                return buf;
              }
              var ieEDGE = navigator.userAgent.match(/Edge/g);
              var ie = navigator.userAgent.match(/.NET/g);
              var oldIE = navigator.userAgent.match(/MSIE/g);
              if (ie || oldIE || ieEDGE) {
                var blob = new window.Blob([ s2ab(wbout)], {
                  type : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                });
                var fileName = '';
                window.navigator.msSaveBlob(blob, fileName);
              } else {
              
                var file = new Blob([s2ab(wbout)], {
                  type : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                });
                var fileURL = window.URL.createObjectURL(file);
                var downloadLink = document.createElement("a");
                downloadLink.download = '';
                downloadLink.innerHTML = "Download File";
                downloadLink.href = fileURL;
                downloadLink.style.display = "none";
                document.body.appendChild(downloadLink);
                downloadLink.click();
              }
            }
    })
  },
   vider() {
      this.candidat.nom = null;
      this.candidat.prenom = null;
      this.candidat.numeroTel = null;
      this.candidat.email = null;
      this.candidat.dateisncription = null;
      this.candidat.technologie = null;
      this.candidat.nomSourceur = null;
      this.candidat.prenomSourceur = null;
      this.candidat.region = null;
      this.candidat.dateInscription = null;
      this.candidat.critereRecheche = null;
    },
     timeStampToDate(timestamp) {
      const date = moment(timestamp)
      return {
        ddmmyyyy: date.format('DD/MM/YYYY')
      }
    },
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

.has-error{
  color : red;
  border-color : red;
  border-block-start-color: red;
  background-color: #fff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(240, 8, 8, 0.25);
}
.danger{
  color: red
}
.star{
  color: red;
  font-weight: bold;
}
.pagination a {
    margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
}

a {
  color: #999;
}
.current {
  color: red;
}
ul {
  padding: 0;
  list-style-type: none;
}
li {
  display: inline;
  margin: 5px 5px;
}

a.first:after {
  content:'...'
}

a.last:before {
  content:'...'
}


</style>

// ADAMING_SUIVI_APP-REST/src/ADAMING_SUIVI_ANGULAR/src/app/views/candidats/listeNouveauxCandidats/listeNouveauxCandidats.component.ts
import { Component, OnInit, ViewChild, OnDestroy } from "@angular/core";
import { CandidateDto } from "../CandidateDto";
import { CandidatsService } from "../../../services/candidats.service";
import { NotifierService } from "angular-notifier";
import { TechnologieService } from "../../../services/administrationService/TechnologieService";
import { HelperService } from "../../../helper/helper.service";
import { Router } from "@angular/router";
import { NAVIGATION_RULES, PHONE_MASK_LABEL, DATE_FORMAT, PHONE_MASK, DATE_FORMAT_MOMENT } from "../../../helper/application.constant";
import { RoutingState } from "../../../helper/routing-state.service";
import * as XLSX from 'xlsx';
import * as FileSaver from 'file-saver';
import { UtilisateurService } from "../../../services/utilisateur.service";
import { RegionService } from "../../../services/administrationService/region.service";
import * as _moment from 'moment';

import { Region } from "../../../models/region";
const EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
const EXCEL_EXTENSION = '.xlsx';

@Component({
  selector: 'ngbd-dropdown-basic',
  templateUrl: 'listeNouveauxCandidats.component.html',
  styleUrls: ["listeNouveauxCandidats.component.css"]

})
export class listeNouveauxCandidatsComponent implements OnInit, OnDestroy {

  titleTable = "List Nouveaux Condidats "

  @ViewChild("table")
  table;

  actions = {
    visible: true,
    title: 'Actions',
    items: [
      {
        icon: 'fa fa-edit',
        class: 'btn-outline-success btn btn-sm',
        tooltip: 'Détails',
        action: (e) => {
          this.openDetails(e);
        }
      },
      {
        icon: 'fa fa-download',
        class: 'btn-outline-warning btn btn-sm',
        tooltip: 'Telecharger CV',
        action:
          (e) => {
            this.downloadCV(e);
          }
      }
    ]
  }

  columns = [
    {
      data: 'nom',
      title: 'Nom',
      visible: true,
    },
    {
      data: 'prenom',
      title: 'Prenom',
      visible: true,
      align: 'center'
    },
    {
      data: 'numeroTel',
      title: 'N° Téléphone',
      visible: true,
      mask: PHONE_MASK_LABEL,
      align: 'center'
    },
    {
      data: 'email',
      title: 'Email',
      visible: true
    },
    {
      data: 'dateInscription',
      title: 'Date inscription',
      visible: true,
      dateFormat: DATE_FORMAT
    },
    {
      data: 'technologie',
      title: 'Type de profil',
      visible: true
    },
    {
      data: 'region',
      title: 'Région',
      visible: true
    },
    {
      data: 'nomSourceur',
      title: 'Nom sourceur',
      visible: true
    },
    {
      data: 'prenomSourceur',
      title: 'Prénom sourceur',
      visible: true
    }
  ]
  mask: any[] = PHONE_MASK;
  technologies = []
  candidats: any[];
  listSourceur: any[];
  condidat: CandidateDto = new CandidateDto();
  CritereRecheche: [
    { value: '1', text: 'Moins 1 mois' },
    { value: '2', text: 'Entre 1 et 6 mois' },
    { value: '3', text: 'Plus de 6 mois' }
  ];
  region: Array<Region> = [];


  constructor(private router: Router,
    private technologiesService: TechnologieService,
    private candidatsService: CandidatsService,
    private helperService: HelperService,
    private routingState: RoutingState,
    private notifierService: NotifierService,
    private utilisateurService: UtilisateurService,
    private regionService: RegionService) {

  }

  ngOnInit(): void {
    if (this.routingState.getPreviousUrl().indexOf('details') > -1)
      this.condidat = this.helperService.listNouveauxCandidatRecherche;
    this.technologiesService.findAllTechnologies().subscribe(data => {
      this.technologies = data;
    }),
      this.utilisateurService.getAllSourceurs().subscribe(data => {
        this.listSourceur = data
      })
  }
  ngOnDestroy(): void {
    this.helperService.listNouveauxCandidatRecherche = this.condidat;
  }
  rechercheCandidat() {
    let callBack = (e) => {
      this.notifierService.notify("info", "Nombre Candidat : " + this.table.maxlenght)
    }
    this.table.setPage(1, callBack);
  }
  initTableFunction() {
    this.rechercheCandidat()
  }
  recherche(item, page, size, allValue) {
    return this.candidatsService.rechercheNouveauxcandidats(item, page, size)
  }

  rechercheNbr(item, allValue) {
    return this.candidatsService.rechercheNouveauxcandidatsNbr(item)
  }

  reset() {
    this.condidat = new CandidateDto();
    this.rechercheCandidat();
  }



  downloadCV(candidat) {
    this.candidatsService.getCvCandidats(candidat).subscribe(res => {
      let file = res;
      var url = window.URL.createObjectURL(file.data);
      var a = document.createElement('a');
      document.body.appendChild(a);
      a.setAttribute('style', 'display: none');
      a.href = url;
      a.download = file.filename;
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove(); // remove the element     

    })
  }

  openDetails(candidat) {
    this.router.navigate([NAVIGATION_RULES.candidats.url + '/' + NAVIGATION_RULES.candidats.details.replace(':id', candidat.id)]);
  }

  public exportAsExcelFile(json: any[], excelFileName: string): void {

    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
    var cell = worksheet["A1"]
    cell.s =   { alignment: {textRotation: 90 }, font: {sz: 14, bold: true, color: "#FF00FF" }} ;
    const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
    const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    this.saveAsExcelFile(excelBuffer, excelFileName);
  }

  private saveAsExcelFile(buffer: any, fileName: string): void {
    const data: Blob = new Blob([buffer], {
      type: EXCEL_TYPE
    });
    FileSaver.saveAs(data, this.titleTable);
  }
  exportAsXLSX(): void {

    this.candidatsService.rechercheNouveauxcandidats(this.table.item, 0, this.table.maxlenght).subscribe(data => {
      var cleanData = [];
      data.forEach(element => {
        var cleanItem = {}
        this.columns.forEach(col => {
          if (element[col.data] != null) {
            if (col.dateFormat != undefined)
              cleanItem[col.title] = _moment(element[col.data]).format(DATE_FORMAT_MOMENT);
            else if (col.mask != undefined && element[col.data].indexOf("-") == -1) {
              cleanItem[col.title] = element[col.data].replace(/^(\d{2})(\d{2})(\d{2})(\d{2})(\d{2}).*/, "$1-$2-$3-$4-$5");
            }
            else cleanItem[col.title] = element[col.data];
          }
        })
        cleanData.push(cleanItem);
      });
      this.exportAsExcelFile(cleanData, 'sample');

    })

  }

  codePostaleOnSearch(value) {
    if (value != "")
      this.regionService.completeRegion(value).subscribe(data => {
        data.forEach(element => {
          this.region = [...  this.region, element]
        });
      })
    else this.region = []
  }
}

<div class="animated fadeIn">
    <div class="row">
        <div class="card">
            <form #rechercheForm="ngForm">
                <div class="card-header">
                    <label style="font-weight:bold;color:#546E7A;">Recherche</label>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="nom" style="font-weight:bold">Nom:</label>
                                <input type="text" class="form-control" name="nom" [(ngModel)]="condidat.nom" id="nom">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="prenom" style="font-weight:bold">Prénom :</label>
                                <input type="text" class="form-control" name="prenom" [(ngModel)]="condidat.prenom" id="prenom">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="numeroTel" style="font-weight:bold">N° téléphone:</label>
                                <input type="text" class="form-control" name="prenom" [(ngModel)]="condidat.numeroTel"
                                    id="numeroTel" [textMask]="{mask: mask}">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="email" style="font-weight:bold">Email:</label>
                                <input type="text" class="form-control" name="email" [(ngModel)]="condidat.email" id="email">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="dateInscription" style="font-weight:bold">Date Inscription:</label>
                               

                                    <input  [owlDateTimeFilter]="dateDateFilter"
                                    [owlDateTimeTrigger]="dateInscription" [owlDateTime]="dateInscription" class="form-control"
                                    name="dateInscription" [(ngModel)]="condidat.dateInscription" id="dateInscription">
                                    <owl-date-time [pickerType]="'calendar'" #dateInscription></owl-date-time>

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="profil" style="font-weight:bold">Type de profil:</label>
                                <select [(ngModel)]="condidat.technologie" name="profil" class="form-control input-sm" id="profil">
                                    <option value="">-- Sélectionner --</option>
                                    <option *ngFor="let tech of technologies" [value]="tech.libelle">{{ tech.libelle }}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="nomSourceur" style="font-weight:bold">Nom Sourceur :</label>
                                <input type="text" class="form-control" name="nomSourceur" [(ngModel)]="condidat.nomSourceur"
                                    id="nomSourceur">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="prenomSourceur" style="font-weight:bold">Prenom Sourceur :</label>
                                <input type="text" class="form-control" name="prenomSourceur" [(ngModel)]="condidat.prenomSourceur"
                                    id="prenomSourceur">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="prenom" style="font-weight:bold">Region:</label>
                                <input type="text" class="form-control" name="region" [(ngModel)]="condidat.region" id="region">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="region" style="font-weight:bold">Fraicheur CV:</label>
                                <select [(ngModel)]="condidat.critereRecheche" name="region" class="form-control input-sm">
                                    <option selected value="">-- Sélectionner --</option>
                                    <option value="1">Moins 1 mois</option>
                                    <option value="2">Entre 1 et 6 mois</option>
                                    <option value="3">Plus de 6 mois</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">

                    <div class="row align-items-center">
                        <div class="col-2">
                            <button type="button" class="btn btn-block btn-primary" (click)="rechercheCandidat()">Rechercher</button>
                        </div>

                        <div class="col-2">
                            <button type="button" class="btn btn-block btn-primary" (click)="reset()" style="float: right;">Réinitialiser</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="card">

            <div class="card-header">
                <label style="font-weight:bold;color:#546E7A;">Liste des nouveaux candidats</label>
            </div>

            <div class="card-body">
                <div autoClose="false" class="btn-group" style="float: right;" dropdown>
                    <button dropdownToggle type="button" class="btn btn-primary dropdown-toggle">
                        Colonnes <span class="caret"></span>
                    </button>
                    <ul (click)="$event.stopPropagation()" class="light" *dropdownMenu class="dropdown-menu" role="menu">
                            <li role="menuitem" *ngFor="let col of columns"> <a class="dropdown-item"><label class="label">
                                    <input class="label__checkbox"
                                    [(ngModel)]="col.visible" type="checkbox" />
                                    <span class="label__text">
                                        <span class="label__check">
                                            <i class="fa fa-check icon"></i>
                                        </span>
                                    </span>
                                </label>>{{col.title}}</a></li>
                       
                    </ul>
                </div>
                <table class="table  table-striped">
                    <thead>
                        <tr>
                            <th [hidden]="!col.visible" *ngFor="let col of columns"> {{col.title }}</th>
                            <th style="width: 120px">ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let c of candidats">
                            <td [hidden]="!col.visible" *ngFor="let col of columns"> {{c[col.data] }}</td>
                            <td style="width: 120px"><button type="button" (click)="openDetails(c)" class="btn btn-outline-primary btn-sm">
                                    <i class="fa fa-edit"></i>
                                </button>
                                <button type="button" style="margin-left: 5px" (click)="downloadCV(c)" class="btn btn-outline-info btn-sm">
                                    <i class="fa fa-download"></i>
                                </button></td>
                        </tr>
                    </tbody>
                </table>
                <ul class="pagination justify-content-center">
                    <li [class.disabled]="1==currentPage" class="page-item">
                        <a (click)="setPage(1)" class="page-link">«</a>
                    </li>
                    <li [class.disabled]="1==currentPage" class="page-item">
                        <a (click)="setPage(currentPage-1)" class="page-link">‹</a>
                    </li>
                    <li [class.active]="p==currentPage" class="page-item" *ngFor=" let p of pages">
                        <a class="page-link" (click)="setPage(p)">{{p}}</a>
                    </li>
                    <li [class.disabled]="currentPage==lastPage" class="page-item">
                        <a (click)="setPage(currentPage+1)" class="page-link">›</a>
                    </li>
                    <li [class.disabled]="currentPage==lastPage" class="page-item">
                        <a (click)="setPage(lastPage)" class="page-link">»</a>
                    </li>
                </ul>
            </div>
            <!--<ngx-loading [show]="loading" [config]=""></ngx-loading>-->
        </div>
    </div>
</div>
