// ADAMING_SUIVI_APP-REST/src/ADAMING_SUIVI_ANGULAR/src/app/views/Sessions-Formations/FicheSessionFormation/FicheSessionFormation.component.ts
import { Component, OnInit } from "@angular/core";
import { DomSanitizer } from "@angular/platform-browser";
import { NotifierService } from "angular-notifier";
import { Router, ActivatedRoute } from '@angular/router';
import { FormationService } from "../../../services/sessionService/formation.service";
import { SessionFormationEnCoursService } from "../../../services/sessionService/session-formation-en-cours.service";
import { TechnologieService } from "../../../services/administrationService/TechnologieService";
import { LieuxService } from "../../../services/administrationService/Lieux.service.";
import { TypeFormationService } from "../../../services/administrationService/TypeFormationService";
import { Formation } from "../formation";


@Component({
  templateUrl: 'FicheSessionFormation.component.html',
  styleUrls:["FicheSessionFormation.component.css"]
})
export class FicheSessionFormationComponent implements OnInit {

  constructor(private sessionFormationService: SessionFormationEnCoursService, private formationService: FormationService,
    private technologiesService: TechnologieService,private lieuxService:LieuxService,private typeFormationService: TypeFormationService,
    private route: ActivatedRoute) { }
  session: any = {}; 
  sessionFormations: any ;
  formations: any;
  t: any = [];
  isCollapsed=[];
  formation: Formation = new Formation();
  //session: Session=new Session();
  technologies = [];
  lieux=[];
  typeFormation=[]
  id: number;
  sub: any;
  ngOnInit() { 
    this.sub = this.route.params.subscribe(params => {
      this.id = +params['id']; 
    });
  }

  getListe(){
  
  }

  



}

<div class="animated fadeIn">
    <div class="row">
        <div class="card">
            <form #rechercheForm="ngForm">
                <div class="card-header">
                    <label style="font-weight:bold;color:#546E7A;">Informations</label>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="nom" style="font-weight:bold">Nom:</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.formation.nom }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="prenom" style="font-weight:bold">Technologie :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.formation.technologie.libelle }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="numeroTel" style="font-weight:bold">Lieu :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.formation.lieu.libelle }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="email" style="font-weight:bold">Type Formation
                                    :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.formation.typeFormation.libelle }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="form-col-form-label" for="dateInscription" style="font-weight:bold">Date
                                    de Demarrage :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.dateDemarrage | date : 'dd/MM/yyyy' }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="profil" style="font-weight:bold">Date Fin :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session?.dateFin | date : 'dd/MM/yyyy' }}</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <label style="font-weight:bold">Nombre Candidats :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ maxlenght }}</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <label style="font-weight:bold">Nombre Place :</label>
                                <div class="col-12">
                                    <p class="form-control-static" style="font-weight: bold;color: black;">{{ session.nombrePlace }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- <div class="card-footer">

                </div> -->
            </form>
        </div>
        <div class="card">
            <div class="card-header">
                <label style="font-weight:bold;color:#546E7A;">Liste Candidats</label>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th> NOM
                            </th>
                            <th>PRENOM
                            </th>
                            <th>N° TEL
                            </th>
                            <th>E-MAIL
                            </th>
                            <th>SOURCEUR
                            </th>
                            <th>Accéptation candidat
                            </th>
                            <th>Refus candidat</th>
                            <th style="width: 100px">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let c of candidats" [class]="c.docConsult==true  ? 'table-success'  :c.docRefus==true  ? 'table-danger' :''">
                            <td>{{c.nom}}</td>
                            <td>{{c.prenom}}</td>
                            <td style="white-space: nowrap;">{{c.numeroTel}}</td>
                            <td>{{c.email}}</td>
                            <td>{{c.creePar.nom }} {{c.creePar.prenom }}</td>
                            <td>
                                <label style="margin-left: 30%;" class="label--checkbox">
                                    <input (change)="modelChanged(c,'docRefus')" class="checkbox" type="checkbox"
                                        [(ngModel)]="c.docConsult" />
                                </label>
                            </td>
                            <td>
                                <label style="margin-left: 30%;" class="label--checkbox">
                                    <input (change)="modelChanged(c,'docConsult')" class="checkbox" type="checkbox"
                                        [(ngModel)]="c.docRefus" />
                                </label>
                            </td>
                            <td style="width: 100px"><button type="button" (click)="openDetails(c)" class="btn btn-outline-success btn-sm">
                                    <i class="fa fa-edit"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="panel-footer panel-default pager">
                    <ul class="pagination justify-content-center">
                        <li [class.disabled]="1==currentPage" class="page-item">
                            <a (click)="setPage(1)" class="page-link">«</a>
                        </li>
                        <li [class.disabled]="1==currentPage" class="page-item">
                            <a (click)="setPage(currentPage-1)" class="page-link">‹</a>
                        </li>
                        <li [class.active]="p==currentPage" class="page-item" *ngFor=" let p of pages">
                            <a class="page-link" (click)="setPage(p)">{{p}}</a>
                        </li>
                        <li [class.disabled]="currentPage==lastPage" class="page-item">
                            <a (click)="setPage(currentPage+1)" class="page-link">›</a>
                        </li>
                        <li [class.disabled]="currentPage==lastPage" class="page-item">
                            <a (click)="setPage(lastPage)" class="page-link">»</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-2">
                        <button (click)="activerDesactiverSession()" type="button" class="btn btn-block btn-primary">{{session.factif
                            != null && session.factif == true ? 'Désactivée Session' :'Activée Session' }}</button>
                    </div>
                    <div class="col-md-8 text-center"><button class="btn btn-sm" (click)="exportAsXLSX()" style="width: 3%;background:#FFFFFF;"  >
                        <img src="assets/excel-icon.png">
                      </button></div>
                    <div class="col-2">
                        <button (click)="annuler()" type="button" class="btn btn-block btn-primary">Annuler</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// ADAMING_SUIVI_APP-REST/src/adaming-suivi-vue/src/views/sessionFormation/ficheSessionFormation.vue
<template>
<div class="row">
<div class="col-sm-12 col-md-12">
<div>
  <div class="card-header">
  <div>
    Informations
 </div>
  </div>
       <b-card-body class="card"  :style="{'direction' : rtl}">
           <b-row>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Nom Formation: </label>
                  <b-form-input  type="text" v-model="session.formation.nom" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Technologie: </label>
                  <b-form-input  type="text" v-model="session.formation.technologie.libelle" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
              <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Lieu: </label>
              <b-form-input  type="text" v-model="session.formation.lieu.libelle" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Type de formation: </label>
                 <b-form-input  type="text" v-model="session.formation.typeFormation.libelle" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
          </b-row>
          <b-row>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Date démarage: </label>
                  <b-form-input  type="text" v-model="timeStampToDate(session.dateDemarrage).ddmmyyyy" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Date fin: </label>
                  <b-form-input  type="text" v-model="timeStampToDate(session.dateFin).ddmmyyyy" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
              <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Nombre Candidats: </label>
              <b-form-input  type="text" v-model="session.nombrePlace" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
            <b-col sm="3">
              <b-form-group>
                <label style="font-weight:bold;color:#546E7A">Nombre Place : </label>
                 <b-form-input  type="text" v-model="session.nombrePlace" disabled=true></b-form-input>
              </b-form-group>
            </b-col>
          </b-row>
      </b-card-body>
</div>
<div class="card"  :style="{'direction' : rtl}" >
  <div class="card-header">
  <div>
  <i class="fa fa-align-justify"></i> 
Liste Candidats
 </div>

  </div>

   <vue-good-table
          :columns= "
          [
        {
          label: 'Nom',
          field: 'nom',
          tdClass: 'text-center',
         
        },
         {
          label: 'Prénom',
          field: 'prenom',
          tdClass: 'text-center',
        
        },
        {
          label: 'N° Téléphone',
          field: 'numeroTel',
          tdClass: 'text-center',
         
        },
        {
          label: 'Email',
          field: 'email',
          tdClass: 'text-center',
         
        },
        {
          label: 'Nom sourceur',
          field: 'nom',
          tdClass: 'text-center',
         
        },
        {
          label: 'Prénom sourceur',
          field: 'prenom',
          tdClass: 'text-center',
        
        },
         {
          label: 'Action',
          field: 'id',
          tdClass: 'text-center',
          type: 'number',
       
        }]"

          :rows="candidats"
          styleClass="vgt-table  bordered vgt-center-align">

            <template slot="table-row" slot-scope="props" >
              <span v-if="props.column.field  == 'nom'">
               {{props.row.nom}}
              </span>
               <span v-if="props.column.field  == 'prenom'">
               {{props.row.prenom}}
              </span>
               <span v-if="props.column.field  == 'numeroTel'">
               {{props.row.numeroTel}}
              </span>
               <span v-if="props.column.field  == 'email'">
               {{props.row.email}}
              </span>
              <span v-if="props.column.field  == 'nom'">
               {{props.row.creePar.nom}}
              </span>
                <span v-if="props.column.field  == 'prenom'">
               {{props.row.creePar.prenom}}
              </span>
              <span v-if="props.column.field  == 'id'">
                <router-link :to="/fiche-entretien/+ props.row.id">
                    <i  class="material-icons text-primary cursor" title="Voir fiche">visibility</i>
                </router-link>
              </span>
            </template>
             <div slot="emptystate">
                Pas des données pour la table
            </div>
       </vue-good-table>
      

    
      
</div>
</div>
</div>
</template>
<script>

 import cSwitch from '@/components/Switch'
 import SessionService from "@/services/sessionService/SessionService";
 import moment from 'moment';
export default {
  components :{
    cSwitch
  },
  data () {
    return {
      session : null,
      candidats : []
    }
  },
  computed: {
    RDVLangue() {
        return this.translate('RDVLangue')
      }
    },
  mounted(){
      var vm = this;
      vm.getcandidatBySession(vm.$route.params.id),
       SessionService.getCandidatBySession(vm.$route.params.id).then(
          function(response) {
            vm.candidats = response.data;

          }
        ) 
        },

  methods: {
 getcandidatBySession(id){
        var vm = this
        SessionService.getSessionByID(id).then(
          function(response) {
            vm.session = response.data;

          }
        )
       

    },
      timeStampToDate(timestamp) {
      const date = moment(timestamp)
      return {
        ddmmyyyy: date.format('DD/MM/YYYY')
      }
    }
  }
}
</script>


</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

.has-error{
  color : red;
  border-color : red;
  border-block-start-color: red;
  background-color: #fff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(240, 8, 8, 0.25);
}
.danger{
  color: red
}
.star{
  color: red;
  font-weight: bold;
}
.pagination a {
    margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
}

a {
  color: #999;
}
.current {
  color: red;
}
ul {
  padding: 0;
  list-style-type: none;
}
li {
  display: inline;
  margin: 5px 5px;
}

a.first:after {
  content:'...'
}

a.last:before {
  content:'...'
}
</style>
